// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: temporal/sdk/core/child_workflow/child_workflow.proto

package childworkflow

import (
	_ "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/corecommon"
	v1 "go.temporal.io/api/common/v1"
	v11 "go.temporal.io/api/failure/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Used by the service to determine the fate of a child workflow
// in case its parent is closed.
type ParentClosePolicy int32

const (
	// Let's the server set the default.
	ParentClosePolicy_PARENT_CLOSE_POLICY_UNSPECIFIED ParentClosePolicy = 0
	// Terminate means terminating the child workflow.
	ParentClosePolicy_PARENT_CLOSE_POLICY_TERMINATE ParentClosePolicy = 1
	// Abandon means not doing anything on the child workflow.
	ParentClosePolicy_PARENT_CLOSE_POLICY_ABANDON ParentClosePolicy = 2
	// Cancel means requesting cancellation on the child workflow.
	ParentClosePolicy_PARENT_CLOSE_POLICY_REQUEST_CANCEL ParentClosePolicy = 3
)

// Enum value maps for ParentClosePolicy.
var (
	ParentClosePolicy_name = map[int32]string{
		0: "PARENT_CLOSE_POLICY_UNSPECIFIED",
		1: "PARENT_CLOSE_POLICY_TERMINATE",
		2: "PARENT_CLOSE_POLICY_ABANDON",
		3: "PARENT_CLOSE_POLICY_REQUEST_CANCEL",
	}
	ParentClosePolicy_value = map[string]int32{
		"PARENT_CLOSE_POLICY_UNSPECIFIED":    0,
		"PARENT_CLOSE_POLICY_TERMINATE":      1,
		"PARENT_CLOSE_POLICY_ABANDON":        2,
		"PARENT_CLOSE_POLICY_REQUEST_CANCEL": 3,
	}
)

func (x ParentClosePolicy) Enum() *ParentClosePolicy {
	p := new(ParentClosePolicy)
	*p = x
	return p
}

func (x ParentClosePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParentClosePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_enumTypes[0].Descriptor()
}

func (ParentClosePolicy) Type() protoreflect.EnumType {
	return &file_temporal_sdk_core_child_workflow_child_workflow_proto_enumTypes[0]
}

func (x ParentClosePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParentClosePolicy.Descriptor instead.
func (ParentClosePolicy) EnumDescriptor() ([]byte, []int) {
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescGZIP(), []int{0}
}

// Possible causes of failure to start a child workflow
type StartChildWorkflowExecutionFailedCause int32

const (
	StartChildWorkflowExecutionFailedCause_START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED             StartChildWorkflowExecutionFailedCause = 0
	StartChildWorkflowExecutionFailedCause_START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS StartChildWorkflowExecutionFailedCause = 1
)

// Enum value maps for StartChildWorkflowExecutionFailedCause.
var (
	StartChildWorkflowExecutionFailedCause_name = map[int32]string{
		0: "START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED",
		1: "START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS",
	}
	StartChildWorkflowExecutionFailedCause_value = map[string]int32{
		"START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED":             0,
		"START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS": 1,
	}
)

func (x StartChildWorkflowExecutionFailedCause) Enum() *StartChildWorkflowExecutionFailedCause {
	p := new(StartChildWorkflowExecutionFailedCause)
	*p = x
	return p
}

func (x StartChildWorkflowExecutionFailedCause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartChildWorkflowExecutionFailedCause) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_enumTypes[1].Descriptor()
}

func (StartChildWorkflowExecutionFailedCause) Type() protoreflect.EnumType {
	return &file_temporal_sdk_core_child_workflow_child_workflow_proto_enumTypes[1]
}

func (x StartChildWorkflowExecutionFailedCause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartChildWorkflowExecutionFailedCause.Descriptor instead.
func (StartChildWorkflowExecutionFailedCause) EnumDescriptor() ([]byte, []int) {
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescGZIP(), []int{1}
}

// Controls at which point to report back to lang when a child workflow is cancelled
type ChildWorkflowCancellationType int32

const (
	// Do not request cancellation of the child workflow if already scheduled
	ChildWorkflowCancellationType_ABANDON ChildWorkflowCancellationType = 0
	// Initiate a cancellation request and immediately report cancellation to the parent.
	ChildWorkflowCancellationType_TRY_CANCEL ChildWorkflowCancellationType = 1
	// Wait for child cancellation completion.
	ChildWorkflowCancellationType_WAIT_CANCELLATION_COMPLETED ChildWorkflowCancellationType = 2
	// Request cancellation of the child and wait for confirmation that the request was received.
	ChildWorkflowCancellationType_WAIT_CANCELLATION_REQUESTED ChildWorkflowCancellationType = 3
)

// Enum value maps for ChildWorkflowCancellationType.
var (
	ChildWorkflowCancellationType_name = map[int32]string{
		0: "ABANDON",
		1: "TRY_CANCEL",
		2: "WAIT_CANCELLATION_COMPLETED",
		3: "WAIT_CANCELLATION_REQUESTED",
	}
	ChildWorkflowCancellationType_value = map[string]int32{
		"ABANDON":                     0,
		"TRY_CANCEL":                  1,
		"WAIT_CANCELLATION_COMPLETED": 2,
		"WAIT_CANCELLATION_REQUESTED": 3,
	}
)

func (x ChildWorkflowCancellationType) Enum() *ChildWorkflowCancellationType {
	p := new(ChildWorkflowCancellationType)
	*p = x
	return p
}

func (x ChildWorkflowCancellationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChildWorkflowCancellationType) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_enumTypes[2].Descriptor()
}

func (ChildWorkflowCancellationType) Type() protoreflect.EnumType {
	return &file_temporal_sdk_core_child_workflow_child_workflow_proto_enumTypes[2]
}

func (x ChildWorkflowCancellationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChildWorkflowCancellationType.Descriptor instead.
func (ChildWorkflowCancellationType) EnumDescriptor() ([]byte, []int) {
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescGZIP(), []int{2}
}

// Used by core to resolve child workflow executions.
type ChildWorkflowResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*ChildWorkflowResult_Completed
	//	*ChildWorkflowResult_Failed
	//	*ChildWorkflowResult_Cancelled
	Status        isChildWorkflowResult_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildWorkflowResult) Reset() {
	*x = ChildWorkflowResult{}
	mi := &file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildWorkflowResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildWorkflowResult) ProtoMessage() {}

func (x *ChildWorkflowResult) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildWorkflowResult.ProtoReflect.Descriptor instead.
func (*ChildWorkflowResult) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *ChildWorkflowResult) GetStatus() isChildWorkflowResult_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ChildWorkflowResult) GetCompleted() *Success {
	if x != nil {
		if x, ok := x.Status.(*ChildWorkflowResult_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *ChildWorkflowResult) GetFailed() *Failure {
	if x != nil {
		if x, ok := x.Status.(*ChildWorkflowResult_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *ChildWorkflowResult) GetCancelled() *Cancellation {
	if x != nil {
		if x, ok := x.Status.(*ChildWorkflowResult_Cancelled); ok {
			return x.Cancelled
		}
	}
	return nil
}

type isChildWorkflowResult_Status interface {
	isChildWorkflowResult_Status()
}

type ChildWorkflowResult_Completed struct {
	Completed *Success `protobuf:"bytes,1,opt,name=completed,proto3,oneof"`
}

type ChildWorkflowResult_Failed struct {
	Failed *Failure `protobuf:"bytes,2,opt,name=failed,proto3,oneof"`
}

type ChildWorkflowResult_Cancelled struct {
	Cancelled *Cancellation `protobuf:"bytes,3,opt,name=cancelled,proto3,oneof"`
}

func (*ChildWorkflowResult_Completed) isChildWorkflowResult_Status() {}

func (*ChildWorkflowResult_Failed) isChildWorkflowResult_Status() {}

func (*ChildWorkflowResult_Cancelled) isChildWorkflowResult_Status() {}

// Used in ChildWorkflowResult to report successful completion.
type Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *v1.Payload            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *Success) GetResult() *v1.Payload {
	if x != nil {
		return x.Result
	}
	return nil
}

// Used in ChildWorkflowResult to report non successful outcomes such as
// application failures, timeouts, terminations, and cancellations.
type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Failure       *v11.Failure           `protobuf:"bytes,1,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *Failure) GetFailure() *v11.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

// Used in ChildWorkflowResult to report cancellation.
// Failure should be ChildWorkflowFailure with a CanceledFailure cause.
type Cancellation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Failure       *v11.Failure           `protobuf:"bytes,1,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancellation) Reset() {
	*x = Cancellation{}
	mi := &file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancellation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancellation) ProtoMessage() {}

func (x *Cancellation) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancellation.ProtoReflect.Descriptor instead.
func (*Cancellation) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *Cancellation) GetFailure() *v11.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

var File_temporal_sdk_core_child_workflow_child_workflow_proto protoreflect.FileDescriptor

const file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDesc = "" +
	"\n" +
	"5temporal/sdk/core/child_workflow/child_workflow.proto\x12\x16coresdk.child_workflow\x1a$temporal/api/common/v1/message.proto\x1a%temporal/api/failure/v1/message.proto\x1a%temporal/sdk/core/common/common.proto\"\xe1\x01\n" +
	"\x13ChildWorkflowResult\x12?\n" +
	"\tcompleted\x18\x01 \x01(\v2\x1f.coresdk.child_workflow.SuccessH\x00R\tcompleted\x129\n" +
	"\x06failed\x18\x02 \x01(\v2\x1f.coresdk.child_workflow.FailureH\x00R\x06failed\x12D\n" +
	"\tcancelled\x18\x03 \x01(\v2$.coresdk.child_workflow.CancellationH\x00R\tcancelledB\b\n" +
	"\x06status\"B\n" +
	"\aSuccess\x127\n" +
	"\x06result\x18\x01 \x01(\v2\x1f.temporal.api.common.v1.PayloadR\x06result\"E\n" +
	"\aFailure\x12:\n" +
	"\afailure\x18\x01 \x01(\v2 .temporal.api.failure.v1.FailureR\afailure\"J\n" +
	"\fCancellation\x12:\n" +
	"\afailure\x18\x01 \x01(\v2 .temporal.api.failure.v1.FailureR\afailure*\xa4\x01\n" +
	"\x11ParentClosePolicy\x12#\n" +
	"\x1fPARENT_CLOSE_POLICY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPARENT_CLOSE_POLICY_TERMINATE\x10\x01\x12\x1f\n" +
	"\x1bPARENT_CLOSE_POLICY_ABANDON\x10\x02\x12&\n" +
	"\"PARENT_CLOSE_POLICY_REQUEST_CANCEL\x10\x03*\xae\x01\n" +
	"&StartChildWorkflowExecutionFailedCause\x12;\n" +
	"7START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED\x10\x00\x12G\n" +
	"CSTART_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS\x10\x01*~\n" +
	"\x1dChildWorkflowCancellationType\x12\v\n" +
	"\aABANDON\x10\x00\x12\x0e\n" +
	"\n" +
	"TRY_CANCEL\x10\x01\x12\x1f\n" +
	"\x1bWAIT_CANCELLATION_COMPLETED\x10\x02\x12\x1f\n" +
	"\x1bWAIT_CANCELLATION_REQUESTED\x10\x03B3\xea\x020Temporalio::Internal::Bridge::Api::ChildWorkflowb\x06proto3"

var (
	file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescOnce sync.Once
	file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescData []byte
)

func file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescGZIP() []byte {
	file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescOnce.Do(func() {
		file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDesc), len(file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDesc)))
	})
	return file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDescData
}

var file_temporal_sdk_core_child_workflow_child_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_temporal_sdk_core_child_workflow_child_workflow_proto_goTypes = []any{
	(ParentClosePolicy)(0),                      // 0: coresdk.child_workflow.ParentClosePolicy
	(StartChildWorkflowExecutionFailedCause)(0), // 1: coresdk.child_workflow.StartChildWorkflowExecutionFailedCause
	(ChildWorkflowCancellationType)(0),          // 2: coresdk.child_workflow.ChildWorkflowCancellationType
	(*ChildWorkflowResult)(nil),                 // 3: coresdk.child_workflow.ChildWorkflowResult
	(*Success)(nil),                             // 4: coresdk.child_workflow.Success
	(*Failure)(nil),                             // 5: coresdk.child_workflow.Failure
	(*Cancellation)(nil),                        // 6: coresdk.child_workflow.Cancellation
	(*v1.Payload)(nil),                          // 7: temporal.api.common.v1.Payload
	(*v11.Failure)(nil),                         // 8: temporal.api.failure.v1.Failure
}
var file_temporal_sdk_core_child_workflow_child_workflow_proto_depIdxs = []int32{
	4, // 0: coresdk.child_workflow.ChildWorkflowResult.completed:type_name -> coresdk.child_workflow.Success
	5, // 1: coresdk.child_workflow.ChildWorkflowResult.failed:type_name -> coresdk.child_workflow.Failure
	6, // 2: coresdk.child_workflow.ChildWorkflowResult.cancelled:type_name -> coresdk.child_workflow.Cancellation
	7, // 3: coresdk.child_workflow.Success.result:type_name -> temporal.api.common.v1.Payload
	8, // 4: coresdk.child_workflow.Failure.failure:type_name -> temporal.api.failure.v1.Failure
	8, // 5: coresdk.child_workflow.Cancellation.failure:type_name -> temporal.api.failure.v1.Failure
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_temporal_sdk_core_child_workflow_child_workflow_proto_init() }
func file_temporal_sdk_core_child_workflow_child_workflow_proto_init() {
	if File_temporal_sdk_core_child_workflow_child_workflow_proto != nil {
		return
	}
	file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes[0].OneofWrappers = []any{
		(*ChildWorkflowResult_Completed)(nil),
		(*ChildWorkflowResult_Failed)(nil),
		(*ChildWorkflowResult_Cancelled)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDesc), len(file_temporal_sdk_core_child_workflow_child_workflow_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_sdk_core_child_workflow_child_workflow_proto_goTypes,
		DependencyIndexes: file_temporal_sdk_core_child_workflow_child_workflow_proto_depIdxs,
		EnumInfos:         file_temporal_sdk_core_child_workflow_child_workflow_proto_enumTypes,
		MessageInfos:      file_temporal_sdk_core_child_workflow_child_workflow_proto_msgTypes,
	}.Build()
	File_temporal_sdk_core_child_workflow_child_workflow_proto = out.File
	file_temporal_sdk_core_child_workflow_child_workflow_proto_goTypes = nil
	file_temporal_sdk_core_child_workflow_child_workflow_proto_depIdxs = nil
}
