// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: temporal/sdk/core/common/common.proto

package corecommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An indication of user's intent concerning what Build ID versioning approach should be used for
// a specific command
type VersioningIntent int32

const (
	// Indicates that core should choose the most sensible default behavior for the type of
	// command, accounting for whether the command will be run on the same task queue as the current
	// worker.
	VersioningIntent_UNSPECIFIED VersioningIntent = 0
	// Indicates that the command should run on a worker with compatible version if possible. It may
	// not be possible if the target task queue does not also have knowledge of the current worker's
	// build ID.
	VersioningIntent_COMPATIBLE VersioningIntent = 1
	// Indicates that the command should run on the target task queue's current overall-default
	// build ID.
	VersioningIntent_DEFAULT VersioningIntent = 2
)

// Enum value maps for VersioningIntent.
var (
	VersioningIntent_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "COMPATIBLE",
		2: "DEFAULT",
	}
	VersioningIntent_value = map[string]int32{
		"UNSPECIFIED": 0,
		"COMPATIBLE":  1,
		"DEFAULT":     2,
	}
)

func (x VersioningIntent) Enum() *VersioningIntent {
	p := new(VersioningIntent)
	*p = x
	return p
}

func (x VersioningIntent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersioningIntent) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_sdk_core_common_common_proto_enumTypes[0].Descriptor()
}

func (VersioningIntent) Type() protoreflect.EnumType {
	return &file_temporal_sdk_core_common_common_proto_enumTypes[0]
}

func (x VersioningIntent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersioningIntent.Descriptor instead.
func (VersioningIntent) EnumDescriptor() ([]byte, []int) {
	return file_temporal_sdk_core_common_common_proto_rawDescGZIP(), []int{0}
}

// Identifying information about a particular workflow execution, including namespace
type NamespacedWorkflowExecution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace the workflow run is located in
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Can never be empty
	WorkflowId string `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// May be empty if the most recent run of the workflow with the given ID is being targeted
	RunId         string `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespacedWorkflowExecution) Reset() {
	*x = NamespacedWorkflowExecution{}
	mi := &file_temporal_sdk_core_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespacedWorkflowExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacedWorkflowExecution) ProtoMessage() {}

func (x *NamespacedWorkflowExecution) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacedWorkflowExecution.ProtoReflect.Descriptor instead.
func (*NamespacedWorkflowExecution) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *NamespacedWorkflowExecution) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespacedWorkflowExecution) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *NamespacedWorkflowExecution) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type WorkerDeploymentVersion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeploymentName string                 `protobuf:"bytes,1,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	BuildId        string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerDeploymentVersion) Reset() {
	*x = WorkerDeploymentVersion{}
	mi := &file_temporal_sdk_core_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerDeploymentVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerDeploymentVersion) ProtoMessage() {}

func (x *WorkerDeploymentVersion) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerDeploymentVersion.ProtoReflect.Descriptor instead.
func (*WorkerDeploymentVersion) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerDeploymentVersion) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *WorkerDeploymentVersion) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

// Metrics for a set of external payload storage operations (all uploads and downloads)
// performed while processing a task, so core can emit unified logging and metrics.
type ExternalStorageMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of payloads stored or retrieved externally.
	PayloadCount uint64 `protobuf:"varint,1,opt,name=payload_count,json=payloadCount,proto3" json:"payload_count,omitempty"`
	// Total size in bytes of the externally stored or retrieved payloads.
	TotalSizeBytes uint64 `protobuf:"varint,2,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	// Wall-clock time spent on the external storage operations.
	TotalDuration *durationpb.Duration `protobuf:"bytes,3,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"`
	// Names of the drivers that participated in the operations.
	DriverNames   []string `protobuf:"bytes,4,rep,name=driver_names,json=driverNames,proto3" json:"driver_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalStorageMetrics) Reset() {
	*x = ExternalStorageMetrics{}
	mi := &file_temporal_sdk_core_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalStorageMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalStorageMetrics) ProtoMessage() {}

func (x *ExternalStorageMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalStorageMetrics.ProtoReflect.Descriptor instead.
func (*ExternalStorageMetrics) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalStorageMetrics) GetPayloadCount() uint64 {
	if x != nil {
		return x.PayloadCount
	}
	return 0
}

func (x *ExternalStorageMetrics) GetTotalSizeBytes() uint64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *ExternalStorageMetrics) GetTotalDuration() *durationpb.Duration {
	if x != nil {
		return x.TotalDuration
	}
	return nil
}

func (x *ExternalStorageMetrics) GetDriverNames() []string {
	if x != nil {
		return x.DriverNames
	}
	return nil
}

var File_temporal_sdk_core_common_common_proto protoreflect.FileDescriptor

const file_temporal_sdk_core_common_common_proto_rawDesc = "" +
	"\n" +
	"%temporal/sdk/core/common/common.proto\x12\x0ecoresdk.common\x1a\x1egoogle/protobuf/duration.proto\"s\n" +
	"\x1bNamespacedWorkflowExecution\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"]\n" +
	"\x17WorkerDeploymentVersion\x12'\n" +
	"\x0fdeployment_name\x18\x01 \x01(\tR\x0edeploymentName\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\"\xcc\x01\n" +
	"\x16ExternalStorageMetrics\x12#\n" +
	"\rpayload_count\x18\x01 \x01(\x04R\fpayloadCount\x12(\n" +
	"\x10total_size_bytes\x18\x02 \x01(\x04R\x0etotalSizeBytes\x12@\n" +
	"\x0etotal_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rtotalDuration\x12!\n" +
	"\fdriver_names\x18\x04 \x03(\tR\vdriverNames*@\n" +
	"\x10VersioningIntent\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"COMPATIBLE\x10\x01\x12\v\n" +
	"\aDEFAULT\x10\x02B,\xea\x02)Temporalio::Internal::Bridge::Api::Commonb\x06proto3"

var (
	file_temporal_sdk_core_common_common_proto_rawDescOnce sync.Once
	file_temporal_sdk_core_common_common_proto_rawDescData []byte
)

func file_temporal_sdk_core_common_common_proto_rawDescGZIP() []byte {
	file_temporal_sdk_core_common_common_proto_rawDescOnce.Do(func() {
		file_temporal_sdk_core_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_common_common_proto_rawDesc), len(file_temporal_sdk_core_common_common_proto_rawDesc)))
	})
	return file_temporal_sdk_core_common_common_proto_rawDescData
}

var file_temporal_sdk_core_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_temporal_sdk_core_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_temporal_sdk_core_common_common_proto_goTypes = []any{
	(VersioningIntent)(0),               // 0: coresdk.common.VersioningIntent
	(*NamespacedWorkflowExecution)(nil), // 1: coresdk.common.NamespacedWorkflowExecution
	(*WorkerDeploymentVersion)(nil),     // 2: coresdk.common.WorkerDeploymentVersion
	(*ExternalStorageMetrics)(nil),      // 3: coresdk.common.ExternalStorageMetrics
	(*durationpb.Duration)(nil),         // 4: google.protobuf.Duration
}
var file_temporal_sdk_core_common_common_proto_depIdxs = []int32{
	4, // 0: coresdk.common.ExternalStorageMetrics.total_duration:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_temporal_sdk_core_common_common_proto_init() }
func file_temporal_sdk_core_common_common_proto_init() {
	if File_temporal_sdk_core_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_common_common_proto_rawDesc), len(file_temporal_sdk_core_common_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_sdk_core_common_common_proto_goTypes,
		DependencyIndexes: file_temporal_sdk_core_common_common_proto_depIdxs,
		EnumInfos:         file_temporal_sdk_core_common_common_proto_enumTypes,
		MessageInfos:      file_temporal_sdk_core_common_common_proto_msgTypes,
	}.Build()
	File_temporal_sdk_core_common_common_proto = out.File
	file_temporal_sdk_core_common_common_proto_goTypes = nil
	file_temporal_sdk_core_common_common_proto_depIdxs = nil
}
