// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: temporal/sdk/core/core_interface.proto

package corepb

import (
	activityresult "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/activityresult"
	_ "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/activitytask"
	_ "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/corecommon"
	_ "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/externaldata"
	_ "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/workflowactivation"
	_ "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/workflowcommands"
	_ "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/workflowcompletion"
	v1 "go.temporal.io/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A request as given to `record_activity_heartbeat`
type ActivityHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskToken     []byte                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	Details       []*v1.Payload          `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityHeartbeat) Reset() {
	*x = ActivityHeartbeat{}
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityHeartbeat) ProtoMessage() {}

func (x *ActivityHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityHeartbeat.ProtoReflect.Descriptor instead.
func (*ActivityHeartbeat) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_core_interface_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityHeartbeat) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *ActivityHeartbeat) GetDetails() []*v1.Payload {
	if x != nil {
		return x.Details
	}
	return nil
}

// A request as given to `complete_activity_task`
type ActivityTaskCompletion struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	TaskToken     []byte                                  `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	Result        *activityresult.ActivityExecutionResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityTaskCompletion) Reset() {
	*x = ActivityTaskCompletion{}
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityTaskCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityTaskCompletion) ProtoMessage() {}

func (x *ActivityTaskCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityTaskCompletion.ProtoReflect.Descriptor instead.
func (*ActivityTaskCompletion) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_core_interface_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityTaskCompletion) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *ActivityTaskCompletion) GetResult() *activityresult.ActivityExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// Info about workflow task slot usage
type WorkflowSlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowType  string                 `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	IsSticky      bool                   `protobuf:"varint,2,opt,name=is_sticky,json=isSticky,proto3" json:"is_sticky,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowSlotInfo) Reset() {
	*x = WorkflowSlotInfo{}
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowSlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowSlotInfo) ProtoMessage() {}

func (x *WorkflowSlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowSlotInfo.ProtoReflect.Descriptor instead.
func (*WorkflowSlotInfo) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_core_interface_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowSlotInfo) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *WorkflowSlotInfo) GetIsSticky() bool {
	if x != nil {
		return x.IsSticky
	}
	return false
}

// Info about activity task slot usage
type ActivitySlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityType  string                 `protobuf:"bytes,1,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivitySlotInfo) Reset() {
	*x = ActivitySlotInfo{}
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivitySlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivitySlotInfo) ProtoMessage() {}

func (x *ActivitySlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivitySlotInfo.ProtoReflect.Descriptor instead.
func (*ActivitySlotInfo) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_core_interface_proto_rawDescGZIP(), []int{3}
}

func (x *ActivitySlotInfo) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

// Info about local activity slot usage
type LocalActivitySlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityType  string                 `protobuf:"bytes,1,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalActivitySlotInfo) Reset() {
	*x = LocalActivitySlotInfo{}
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalActivitySlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalActivitySlotInfo) ProtoMessage() {}

func (x *LocalActivitySlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalActivitySlotInfo.ProtoReflect.Descriptor instead.
func (*LocalActivitySlotInfo) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_core_interface_proto_rawDescGZIP(), []int{4}
}

func (x *LocalActivitySlotInfo) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

// Info about nexus task slot usage
type NexusSlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NexusSlotInfo) Reset() {
	*x = NexusSlotInfo{}
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NexusSlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusSlotInfo) ProtoMessage() {}

func (x *NexusSlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusSlotInfo.ProtoReflect.Descriptor instead.
func (*NexusSlotInfo) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_core_interface_proto_rawDescGZIP(), []int{5}
}

func (x *NexusSlotInfo) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *NexusSlotInfo) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// Info about a namespace
type NamespaceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace configured limits
	Limits        *NamespaceInfo_Limits `protobuf:"bytes,1,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceInfo) Reset() {
	*x = NamespaceInfo{}
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceInfo) ProtoMessage() {}

func (x *NamespaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceInfo.ProtoReflect.Descriptor instead.
func (*NamespaceInfo) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_core_interface_proto_rawDescGZIP(), []int{6}
}

func (x *NamespaceInfo) GetLimits() *NamespaceInfo_Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type NamespaceInfo_Limits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum size in bytes for payload fields in workflow history events
	// (e.g., workflow/activity inputs and results, failure details, signal payloads).
	// When exceeded, the server will reject the operation with an error.
	BlobSizeLimitError int64 `protobuf:"varint,1,opt,name=blob_size_limit_error,json=blobSizeLimitError,proto3" json:"blob_size_limit_error,omitempty"`
	// Maximum total memo size in bytes per workflow execution.
	MemoSizeLimitError int64 `protobuf:"varint,2,opt,name=memo_size_limit_error,json=memoSizeLimitError,proto3" json:"memo_size_limit_error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NamespaceInfo_Limits) Reset() {
	*x = NamespaceInfo_Limits{}
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceInfo_Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceInfo_Limits) ProtoMessage() {}

func (x *NamespaceInfo_Limits) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_core_interface_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceInfo_Limits.ProtoReflect.Descriptor instead.
func (*NamespaceInfo_Limits) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_core_interface_proto_rawDescGZIP(), []int{6, 0}
}

func (x *NamespaceInfo_Limits) GetBlobSizeLimitError() int64 {
	if x != nil {
		return x.BlobSizeLimitError
	}
	return 0
}

func (x *NamespaceInfo_Limits) GetMemoSizeLimitError() int64 {
	if x != nil {
		return x.MemoSizeLimitError
	}
	return 0
}

var File_temporal_sdk_core_core_interface_proto protoreflect.FileDescriptor

const file_temporal_sdk_core_core_interface_proto_rawDesc = "" +
	"\n" +
	"&temporal/sdk/core/core_interface.proto\x12\acoresdk\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$temporal/api/common/v1/message.proto\x1a7temporal/sdk/core/activity_result/activity_result.proto\x1a3temporal/sdk/core/activity_task/activity_task.proto\x1a%temporal/sdk/core/common/common.proto\x1a3temporal/sdk/core/external_data/external_data.proto\x1a?temporal/sdk/core/workflow_activation/workflow_activation.proto\x1a;temporal/sdk/core/workflow_commands/workflow_commands.proto\x1a?temporal/sdk/core/workflow_completion/workflow_completion.proto\"m\n" +
	"\x11ActivityHeartbeat\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x129\n" +
	"\adetails\x18\x02 \x03(\v2\x1f.temporal.api.common.v1.PayloadR\adetails\"\x81\x01\n" +
	"\x16ActivityTaskCompletion\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12H\n" +
	"\x06result\x18\x02 \x01(\v20.coresdk.activity_result.ActivityExecutionResultR\x06result\"T\n" +
	"\x10WorkflowSlotInfo\x12#\n" +
	"\rworkflow_type\x18\x01 \x01(\tR\fworkflowType\x12\x1b\n" +
	"\tis_sticky\x18\x02 \x01(\bR\bisSticky\"7\n" +
	"\x10ActivitySlotInfo\x12#\n" +
	"\ractivity_type\x18\x01 \x01(\tR\factivityType\"<\n" +
	"\x15LocalActivitySlotInfo\x12#\n" +
	"\ractivity_type\x18\x01 \x01(\tR\factivityType\"G\n" +
	"\rNexusSlotInfo\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"\xb6\x01\n" +
	"\rNamespaceInfo\x125\n" +
	"\x06limits\x18\x01 \x01(\v2\x1d.coresdk.NamespaceInfo.LimitsR\x06limits\x1an\n" +
	"\x06Limits\x121\n" +
	"\x15blob_size_limit_error\x18\x01 \x01(\x03R\x12blobSizeLimitError\x121\n" +
	"\x15memo_size_limit_error\x18\x02 \x01(\x03R\x12memoSizeLimitErrorB3\xea\x020Temporalio::Internal::Bridge::Api::CoreInterfaceb\x06proto3"

var (
	file_temporal_sdk_core_core_interface_proto_rawDescOnce sync.Once
	file_temporal_sdk_core_core_interface_proto_rawDescData []byte
)

func file_temporal_sdk_core_core_interface_proto_rawDescGZIP() []byte {
	file_temporal_sdk_core_core_interface_proto_rawDescOnce.Do(func() {
		file_temporal_sdk_core_core_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_core_interface_proto_rawDesc), len(file_temporal_sdk_core_core_interface_proto_rawDesc)))
	})
	return file_temporal_sdk_core_core_interface_proto_rawDescData
}

var file_temporal_sdk_core_core_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_temporal_sdk_core_core_interface_proto_goTypes = []any{
	(*ActivityHeartbeat)(nil),                      // 0: coresdk.ActivityHeartbeat
	(*ActivityTaskCompletion)(nil),                 // 1: coresdk.ActivityTaskCompletion
	(*WorkflowSlotInfo)(nil),                       // 2: coresdk.WorkflowSlotInfo
	(*ActivitySlotInfo)(nil),                       // 3: coresdk.ActivitySlotInfo
	(*LocalActivitySlotInfo)(nil),                  // 4: coresdk.LocalActivitySlotInfo
	(*NexusSlotInfo)(nil),                          // 5: coresdk.NexusSlotInfo
	(*NamespaceInfo)(nil),                          // 6: coresdk.NamespaceInfo
	(*NamespaceInfo_Limits)(nil),                   // 7: coresdk.NamespaceInfo.Limits
	(*v1.Payload)(nil),                             // 8: temporal.api.common.v1.Payload
	(*activityresult.ActivityExecutionResult)(nil), // 9: coresdk.activity_result.ActivityExecutionResult
}
var file_temporal_sdk_core_core_interface_proto_depIdxs = []int32{
	8, // 0: coresdk.ActivityHeartbeat.details:type_name -> temporal.api.common.v1.Payload
	9, // 1: coresdk.ActivityTaskCompletion.result:type_name -> coresdk.activity_result.ActivityExecutionResult
	7, // 2: coresdk.NamespaceInfo.limits:type_name -> coresdk.NamespaceInfo.Limits
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_temporal_sdk_core_core_interface_proto_init() }
func file_temporal_sdk_core_core_interface_proto_init() {
	if File_temporal_sdk_core_core_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_core_interface_proto_rawDesc), len(file_temporal_sdk_core_core_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_sdk_core_core_interface_proto_goTypes,
		DependencyIndexes: file_temporal_sdk_core_core_interface_proto_depIdxs,
		MessageInfos:      file_temporal_sdk_core_core_interface_proto_msgTypes,
	}.Build()
	File_temporal_sdk_core_core_interface_proto = out.File
	file_temporal_sdk_core_core_interface_proto_goTypes = nil
	file_temporal_sdk_core_core_interface_proto_depIdxs = nil
}
