// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: temporal/sdk/core/wasm_bridge/wasm_bridge.proto

package wasmbridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A unary gRPC request sent from Temporal Core to the Go host transport.
type GrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Rpc           string                 `protobuf:"bytes,3,opt,name=rpc,proto3" json:"rpc,omitempty"`
	Metadata      []*MetadataEntry       `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty"`
	Proto         []byte                 `protobuf:"bytes,5,opt,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcRequest) Reset() {
	*x = GrpcRequest{}
	mi := &file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcRequest) ProtoMessage() {}

func (x *GrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcRequest.ProtoReflect.Descriptor instead.
func (*GrpcRequest) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GrpcRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GrpcRequest) GetRpc() string {
	if x != nil {
		return x.Rpc
	}
	return ""
}

func (x *GrpcRequest) GetMetadata() []*MetadataEntry {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GrpcRequest) GetProto() []byte {
	if x != nil {
		return x.Proto
	}
	return nil
}

// A unary gRPC response returned by the Go host transport to Temporal Core.
type GrpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Headers       []*MetadataEntry       `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Trailers      []*MetadataEntry       `protobuf:"bytes,4,rep,name=trailers,proto3" json:"trailers,omitempty"`
	StatusDetails []byte                 `protobuf:"bytes,5,opt,name=status_details,json=statusDetails,proto3" json:"status_details,omitempty"`
	Proto         []byte                 `protobuf:"bytes,6,opt,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcResponse) Reset() {
	*x = GrpcResponse{}
	mi := &file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcResponse) ProtoMessage() {}

func (x *GrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcResponse.ProtoReflect.Descriptor instead.
func (*GrpcResponse) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GrpcResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *GrpcResponse) GetHeaders() []*MetadataEntry {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GrpcResponse) GetTrailers() []*MetadataEntry {
	if x != nil {
		return x.Trailers
	}
	return nil
}

func (x *GrpcResponse) GetStatusDetails() []byte {
	if x != nil {
		return x.StatusDetails
	}
	return nil
}

func (x *GrpcResponse) GetProto() []byte {
	if x != nil {
		return x.Proto
	}
	return nil
}

// One gRPC metadata value. Repeated entries preserve duplicate values and their
// order. Values use the decoded gRPC representation, including raw binary
// values for keys ending in "-bin".
type MetadataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataEntry) Reset() {
	*x = MetadataEntry{}
	mi := &file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEntry) ProtoMessage() {}

func (x *MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataEntry.ProtoReflect.Descriptor instead.
func (*MetadataEntry) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_temporal_sdk_core_wasm_bridge_wasm_bridge_proto protoreflect.FileDescriptor

const file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDesc = "" +
	"\n" +
	"/temporal/sdk/core/wasm_bridge/wasm_bridge.proto\x12\x13coresdk.wasm_bridge\"\x9f\x01\n" +
	"\vGrpcRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x10\n" +
	"\x03rpc\x18\x03 \x01(\tR\x03rpc\x12>\n" +
	"\bmetadata\x18\x04 \x03(\v2\".coresdk.wasm_bridge.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05proto\x18\x05 \x01(\fR\x05proto\"\x91\x02\n" +
	"\fGrpcResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12<\n" +
	"\aheaders\x18\x03 \x03(\v2\".coresdk.wasm_bridge.MetadataEntryR\aheaders\x12>\n" +
	"\btrailers\x18\x04 \x03(\v2\".coresdk.wasm_bridge.MetadataEntryR\btrailers\x12%\n" +
	"\x0estatus_details\x18\x05 \x01(\fR\rstatusDetails\x12\x14\n" +
	"\x05proto\x18\x06 \x01(\fR\x05proto\"7\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05valueb\x06proto3"

var (
	file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDescOnce sync.Once
	file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDescData []byte
)

func file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDescGZIP() []byte {
	file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDescOnce.Do(func() {
		file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDesc), len(file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDesc)))
	})
	return file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDescData
}

var file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_goTypes = []any{
	(*GrpcRequest)(nil),   // 0: coresdk.wasm_bridge.GrpcRequest
	(*GrpcResponse)(nil),  // 1: coresdk.wasm_bridge.GrpcResponse
	(*MetadataEntry)(nil), // 2: coresdk.wasm_bridge.MetadataEntry
}
var file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_depIdxs = []int32{
	2, // 0: coresdk.wasm_bridge.GrpcRequest.metadata:type_name -> coresdk.wasm_bridge.MetadataEntry
	2, // 1: coresdk.wasm_bridge.GrpcResponse.headers:type_name -> coresdk.wasm_bridge.MetadataEntry
	2, // 2: coresdk.wasm_bridge.GrpcResponse.trailers:type_name -> coresdk.wasm_bridge.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_init() }
func file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_init() {
	if File_temporal_sdk_core_wasm_bridge_wasm_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDesc), len(file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_goTypes,
		DependencyIndexes: file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_depIdxs,
		MessageInfos:      file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_msgTypes,
	}.Build()
	File_temporal_sdk_core_wasm_bridge_wasm_bridge_proto = out.File
	file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_goTypes = nil
	file_temporal_sdk_core_wasm_bridge_wasm_bridge_proto_depIdxs = nil
}
