// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: temporal/sdk/core/activity_task/activity_task.proto

//*
// Definitions of the different activity tasks returned from [crate::Core::poll_task].

package activitytask

import (
	_ "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/corecommon"
	v1 "go.temporal.io/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityCancelReason int32

const (
	// The activity no longer exists according to server (may be already completed)
	ActivityCancelReason_NOT_FOUND ActivityCancelReason = 0
	// Activity was explicitly cancelled
	ActivityCancelReason_CANCELLED ActivityCancelReason = 1
	// Activity timed out
	ActivityCancelReason_TIMED_OUT ActivityCancelReason = 2
	// Core is shutting down and the graceful timeout has elapsed
	ActivityCancelReason_WORKER_SHUTDOWN ActivityCancelReason = 3
	// Activity was paused
	ActivityCancelReason_PAUSED ActivityCancelReason = 4
	// Activity was reset
	ActivityCancelReason_RESET ActivityCancelReason = 5
)

// Enum value maps for ActivityCancelReason.
var (
	ActivityCancelReason_name = map[int32]string{
		0: "NOT_FOUND",
		1: "CANCELLED",
		2: "TIMED_OUT",
		3: "WORKER_SHUTDOWN",
		4: "PAUSED",
		5: "RESET",
	}
	ActivityCancelReason_value = map[string]int32{
		"NOT_FOUND":       0,
		"CANCELLED":       1,
		"TIMED_OUT":       2,
		"WORKER_SHUTDOWN": 3,
		"PAUSED":          4,
		"RESET":           5,
	}
)

func (x ActivityCancelReason) Enum() *ActivityCancelReason {
	p := new(ActivityCancelReason)
	*p = x
	return p
}

func (x ActivityCancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityCancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_sdk_core_activity_task_activity_task_proto_enumTypes[0].Descriptor()
}

func (ActivityCancelReason) Type() protoreflect.EnumType {
	return &file_temporal_sdk_core_activity_task_activity_task_proto_enumTypes[0]
}

func (x ActivityCancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityCancelReason.Descriptor instead.
func (ActivityCancelReason) EnumDescriptor() ([]byte, []int) {
	return file_temporal_sdk_core_activity_task_activity_task_proto_rawDescGZIP(), []int{0}
}

type ActivityTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique identifier for this task
	TaskToken []byte `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	// Types that are valid to be assigned to Variant:
	//
	//	*ActivityTask_Start
	//	*ActivityTask_Cancel
	Variant       isActivityTask_Variant `protobuf_oneof:"variant"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityTask) Reset() {
	*x = ActivityTask{}
	mi := &file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityTask) ProtoMessage() {}

func (x *ActivityTask) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityTask.ProtoReflect.Descriptor instead.
func (*ActivityTask) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_activity_task_activity_task_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityTask) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *ActivityTask) GetVariant() isActivityTask_Variant {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *ActivityTask) GetStart() *Start {
	if x != nil {
		if x, ok := x.Variant.(*ActivityTask_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ActivityTask) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Variant.(*ActivityTask_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isActivityTask_Variant interface {
	isActivityTask_Variant()
}

type ActivityTask_Start struct {
	// Start activity execution.
	Start *Start `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type ActivityTask_Cancel struct {
	// Attempt to cancel activity execution.
	Cancel *Cancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*ActivityTask_Start) isActivityTask_Variant() {}

func (*ActivityTask_Cancel) isActivityTask_Variant() {}

// Begin executing an activity
type Start struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace the workflow lives in
	WorkflowNamespace string `protobuf:"bytes,1,opt,name=workflow_namespace,json=workflowNamespace,proto3" json:"workflow_namespace,omitempty"`
	// The workflow's type name or function identifier
	WorkflowType string `protobuf:"bytes,2,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	// The workflow execution which requested this activity
	WorkflowExecution *v1.WorkflowExecution `protobuf:"bytes,3,opt,name=workflow_execution,json=workflowExecution,proto3" json:"workflow_execution,omitempty"`
	// The activity's ID
	ActivityId string `protobuf:"bytes,4,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	// The activity's type name or function identifier
	ActivityType string                 `protobuf:"bytes,5,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	HeaderFields map[string]*v1.Payload `protobuf:"bytes,6,rep,name=header_fields,json=headerFields,proto3" json:"header_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Arguments to the activity
	Input []*v1.Payload `protobuf:"bytes,7,rep,name=input,proto3" json:"input,omitempty"`
	// The last details that were recorded by a heartbeat when this task was generated
	HeartbeatDetails []*v1.Payload `protobuf:"bytes,8,rep,name=heartbeat_details,json=heartbeatDetails,proto3" json:"heartbeat_details,omitempty"`
	// When the task was *first* scheduled
	ScheduledTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	// When this current attempt at the task was scheduled
	CurrentAttemptScheduledTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=current_attempt_scheduled_time,json=currentAttemptScheduledTime,proto3" json:"current_attempt_scheduled_time,omitempty"`
	// When this attempt was started, which is to say when core received it by polling.
	StartedTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_time,json=startedTime,proto3" json:"started_time,omitempty"`
	Attempt     uint32                 `protobuf:"varint,12,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Timeout from the first schedule time to completion
	ScheduleToCloseTimeout *durationpb.Duration `protobuf:"bytes,13,opt,name=schedule_to_close_timeout,json=scheduleToCloseTimeout,proto3" json:"schedule_to_close_timeout,omitempty"`
	// Timeout from starting an attempt to reporting its result
	StartToCloseTimeout *durationpb.Duration `protobuf:"bytes,14,opt,name=start_to_close_timeout,json=startToCloseTimeout,proto3" json:"start_to_close_timeout,omitempty"`
	// If set a heartbeat must be reported within this interval
	HeartbeatTimeout *durationpb.Duration `protobuf:"bytes,15,opt,name=heartbeat_timeout,json=heartbeatTimeout,proto3" json:"heartbeat_timeout,omitempty"`
	// This is an actual retry policy the service uses. It can be different from the one provided
	// (or not) during activity scheduling as the service can override the provided one in case its
	// values are not specified or exceed configured system limits.
	RetryPolicy *v1.RetryPolicy `protobuf:"bytes,16,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	// Priority of this activity. Local activities will always have this field set to the default.
	Priority *v1.Priority `protobuf:"bytes,18,opt,name=priority,proto3" json:"priority,omitempty"`
	// Set to true if this is a local activity. Note that heartbeating does not apply to local
	// activities.
	IsLocal bool `protobuf:"varint,17,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`
	// Run ID of this activity execution. Only set for standalone activities.
	RunId         string `protobuf:"bytes,19,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Start) Reset() {
	*x = Start{}
	mi := &file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_activity_task_activity_task_proto_rawDescGZIP(), []int{1}
}

func (x *Start) GetWorkflowNamespace() string {
	if x != nil {
		return x.WorkflowNamespace
	}
	return ""
}

func (x *Start) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *Start) GetWorkflowExecution() *v1.WorkflowExecution {
	if x != nil {
		return x.WorkflowExecution
	}
	return nil
}

func (x *Start) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *Start) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *Start) GetHeaderFields() map[string]*v1.Payload {
	if x != nil {
		return x.HeaderFields
	}
	return nil
}

func (x *Start) GetInput() []*v1.Payload {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Start) GetHeartbeatDetails() []*v1.Payload {
	if x != nil {
		return x.HeartbeatDetails
	}
	return nil
}

func (x *Start) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *Start) GetCurrentAttemptScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentAttemptScheduledTime
	}
	return nil
}

func (x *Start) GetStartedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedTime
	}
	return nil
}

func (x *Start) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Start) GetScheduleToCloseTimeout() *durationpb.Duration {
	if x != nil {
		return x.ScheduleToCloseTimeout
	}
	return nil
}

func (x *Start) GetStartToCloseTimeout() *durationpb.Duration {
	if x != nil {
		return x.StartToCloseTimeout
	}
	return nil
}

func (x *Start) GetHeartbeatTimeout() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatTimeout
	}
	return nil
}

func (x *Start) GetRetryPolicy() *v1.RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *Start) GetPriority() *v1.Priority {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *Start) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *Start) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// Attempt to cancel a running activity
type Cancel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primary cancellation reason
	Reason ActivityCancelReason `protobuf:"varint,1,opt,name=reason,proto3,enum=coresdk.activity_task.ActivityCancelReason" json:"reason,omitempty"`
	// Activity cancellation details, surfaces all cancellation reasons.
	Details       *ActivityCancellationDetails `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_activity_task_activity_task_proto_rawDescGZIP(), []int{2}
}

func (x *Cancel) GetReason() ActivityCancelReason {
	if x != nil {
		return x.Reason
	}
	return ActivityCancelReason_NOT_FOUND
}

func (x *Cancel) GetDetails() *ActivityCancellationDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type ActivityCancellationDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsNotFound       bool                   `protobuf:"varint,1,opt,name=is_not_found,json=isNotFound,proto3" json:"is_not_found,omitempty"`
	IsCancelled      bool                   `protobuf:"varint,2,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	IsPaused         bool                   `protobuf:"varint,3,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
	IsTimedOut       bool                   `protobuf:"varint,4,opt,name=is_timed_out,json=isTimedOut,proto3" json:"is_timed_out,omitempty"`
	IsWorkerShutdown bool                   `protobuf:"varint,5,opt,name=is_worker_shutdown,json=isWorkerShutdown,proto3" json:"is_worker_shutdown,omitempty"`
	IsReset          bool                   `protobuf:"varint,6,opt,name=is_reset,json=isReset,proto3" json:"is_reset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActivityCancellationDetails) Reset() {
	*x = ActivityCancellationDetails{}
	mi := &file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityCancellationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityCancellationDetails) ProtoMessage() {}

func (x *ActivityCancellationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityCancellationDetails.ProtoReflect.Descriptor instead.
func (*ActivityCancellationDetails) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_activity_task_activity_task_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityCancellationDetails) GetIsNotFound() bool {
	if x != nil {
		return x.IsNotFound
	}
	return false
}

func (x *ActivityCancellationDetails) GetIsCancelled() bool {
	if x != nil {
		return x.IsCancelled
	}
	return false
}

func (x *ActivityCancellationDetails) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

func (x *ActivityCancellationDetails) GetIsTimedOut() bool {
	if x != nil {
		return x.IsTimedOut
	}
	return false
}

func (x *ActivityCancellationDetails) GetIsWorkerShutdown() bool {
	if x != nil {
		return x.IsWorkerShutdown
	}
	return false
}

func (x *ActivityCancellationDetails) GetIsReset() bool {
	if x != nil {
		return x.IsReset
	}
	return false
}

var File_temporal_sdk_core_activity_task_activity_task_proto protoreflect.FileDescriptor

const file_temporal_sdk_core_activity_task_activity_task_proto_rawDesc = "" +
	"\n" +
	"3temporal/sdk/core/activity_task/activity_task.proto\x12\x15coresdk.activity_task\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$temporal/api/common/v1/message.proto\x1a%temporal/sdk/core/common/common.proto\"\xa7\x01\n" +
	"\fActivityTask\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x124\n" +
	"\x05start\x18\x03 \x01(\v2\x1c.coresdk.activity_task.StartH\x00R\x05start\x127\n" +
	"\x06cancel\x18\x04 \x01(\v2\x1d.coresdk.activity_task.CancelH\x00R\x06cancelB\t\n" +
	"\avariant\"\xda\t\n" +
	"\x05Start\x12-\n" +
	"\x12workflow_namespace\x18\x01 \x01(\tR\x11workflowNamespace\x12#\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\fworkflowType\x12X\n" +
	"\x12workflow_execution\x18\x03 \x01(\v2).temporal.api.common.v1.WorkflowExecutionR\x11workflowExecution\x12\x1f\n" +
	"\vactivity_id\x18\x04 \x01(\tR\n" +
	"activityId\x12#\n" +
	"\ractivity_type\x18\x05 \x01(\tR\factivityType\x12S\n" +
	"\rheader_fields\x18\x06 \x03(\v2..coresdk.activity_task.Start.HeaderFieldsEntryR\fheaderFields\x125\n" +
	"\x05input\x18\a \x03(\v2\x1f.temporal.api.common.v1.PayloadR\x05input\x12L\n" +
	"\x11heartbeat_details\x18\b \x03(\v2\x1f.temporal.api.common.v1.PayloadR\x10heartbeatDetails\x12A\n" +
	"\x0escheduled_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x12_\n" +
	"\x1ecurrent_attempt_scheduled_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x1bcurrentAttemptScheduledTime\x12=\n" +
	"\fstarted_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vstartedTime\x12\x18\n" +
	"\aattempt\x18\f \x01(\rR\aattempt\x12T\n" +
	"\x19schedule_to_close_timeout\x18\r \x01(\v2\x19.google.protobuf.DurationR\x16scheduleToCloseTimeout\x12N\n" +
	"\x16start_to_close_timeout\x18\x0e \x01(\v2\x19.google.protobuf.DurationR\x13startToCloseTimeout\x12F\n" +
	"\x11heartbeat_timeout\x18\x0f \x01(\v2\x19.google.protobuf.DurationR\x10heartbeatTimeout\x12F\n" +
	"\fretry_policy\x18\x10 \x01(\v2#.temporal.api.common.v1.RetryPolicyR\vretryPolicy\x12<\n" +
	"\bpriority\x18\x12 \x01(\v2 .temporal.api.common.v1.PriorityR\bpriority\x12\x19\n" +
	"\bis_local\x18\x11 \x01(\bR\aisLocal\x12\x15\n" +
	"\x06run_id\x18\x13 \x01(\tR\x05runId\x1a`\n" +
	"\x11HeaderFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.temporal.api.common.v1.PayloadR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x06Cancel\x12C\n" +
	"\x06reason\x18\x01 \x01(\x0e2+.coresdk.activity_task.ActivityCancelReasonR\x06reason\x12L\n" +
	"\adetails\x18\x02 \x01(\v22.coresdk.activity_task.ActivityCancellationDetailsR\adetails\"\xea\x01\n" +
	"\x1bActivityCancellationDetails\x12 \n" +
	"\fis_not_found\x18\x01 \x01(\bR\n" +
	"isNotFound\x12!\n" +
	"\fis_cancelled\x18\x02 \x01(\bR\visCancelled\x12\x1b\n" +
	"\tis_paused\x18\x03 \x01(\bR\bisPaused\x12 \n" +
	"\fis_timed_out\x18\x04 \x01(\bR\n" +
	"isTimedOut\x12,\n" +
	"\x12is_worker_shutdown\x18\x05 \x01(\bR\x10isWorkerShutdown\x12\x19\n" +
	"\bis_reset\x18\x06 \x01(\bR\aisReset*o\n" +
	"\x14ActivityCancelReason\x12\r\n" +
	"\tNOT_FOUND\x10\x00\x12\r\n" +
	"\tCANCELLED\x10\x01\x12\r\n" +
	"\tTIMED_OUT\x10\x02\x12\x13\n" +
	"\x0fWORKER_SHUTDOWN\x10\x03\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x04\x12\t\n" +
	"\x05RESET\x10\x05B2\xea\x02/Temporalio::Internal::Bridge::Api::ActivityTaskb\x06proto3"

var (
	file_temporal_sdk_core_activity_task_activity_task_proto_rawDescOnce sync.Once
	file_temporal_sdk_core_activity_task_activity_task_proto_rawDescData []byte
)

func file_temporal_sdk_core_activity_task_activity_task_proto_rawDescGZIP() []byte {
	file_temporal_sdk_core_activity_task_activity_task_proto_rawDescOnce.Do(func() {
		file_temporal_sdk_core_activity_task_activity_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_activity_task_activity_task_proto_rawDesc), len(file_temporal_sdk_core_activity_task_activity_task_proto_rawDesc)))
	})
	return file_temporal_sdk_core_activity_task_activity_task_proto_rawDescData
}

var file_temporal_sdk_core_activity_task_activity_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_temporal_sdk_core_activity_task_activity_task_proto_goTypes = []any{
	(ActivityCancelReason)(0),           // 0: coresdk.activity_task.ActivityCancelReason
	(*ActivityTask)(nil),                // 1: coresdk.activity_task.ActivityTask
	(*Start)(nil),                       // 2: coresdk.activity_task.Start
	(*Cancel)(nil),                      // 3: coresdk.activity_task.Cancel
	(*ActivityCancellationDetails)(nil), // 4: coresdk.activity_task.ActivityCancellationDetails
	nil,                                 // 5: coresdk.activity_task.Start.HeaderFieldsEntry
	(*v1.WorkflowExecution)(nil),        // 6: temporal.api.common.v1.WorkflowExecution
	(*v1.Payload)(nil),                  // 7: temporal.api.common.v1.Payload
	(*timestamppb.Timestamp)(nil),       // 8: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),         // 9: google.protobuf.Duration
	(*v1.RetryPolicy)(nil),              // 10: temporal.api.common.v1.RetryPolicy
	(*v1.Priority)(nil),                 // 11: temporal.api.common.v1.Priority
}
var file_temporal_sdk_core_activity_task_activity_task_proto_depIdxs = []int32{
	2,  // 0: coresdk.activity_task.ActivityTask.start:type_name -> coresdk.activity_task.Start
	3,  // 1: coresdk.activity_task.ActivityTask.cancel:type_name -> coresdk.activity_task.Cancel
	6,  // 2: coresdk.activity_task.Start.workflow_execution:type_name -> temporal.api.common.v1.WorkflowExecution
	5,  // 3: coresdk.activity_task.Start.header_fields:type_name -> coresdk.activity_task.Start.HeaderFieldsEntry
	7,  // 4: coresdk.activity_task.Start.input:type_name -> temporal.api.common.v1.Payload
	7,  // 5: coresdk.activity_task.Start.heartbeat_details:type_name -> temporal.api.common.v1.Payload
	8,  // 6: coresdk.activity_task.Start.scheduled_time:type_name -> google.protobuf.Timestamp
	8,  // 7: coresdk.activity_task.Start.current_attempt_scheduled_time:type_name -> google.protobuf.Timestamp
	8,  // 8: coresdk.activity_task.Start.started_time:type_name -> google.protobuf.Timestamp
	9,  // 9: coresdk.activity_task.Start.schedule_to_close_timeout:type_name -> google.protobuf.Duration
	9,  // 10: coresdk.activity_task.Start.start_to_close_timeout:type_name -> google.protobuf.Duration
	9,  // 11: coresdk.activity_task.Start.heartbeat_timeout:type_name -> google.protobuf.Duration
	10, // 12: coresdk.activity_task.Start.retry_policy:type_name -> temporal.api.common.v1.RetryPolicy
	11, // 13: coresdk.activity_task.Start.priority:type_name -> temporal.api.common.v1.Priority
	0,  // 14: coresdk.activity_task.Cancel.reason:type_name -> coresdk.activity_task.ActivityCancelReason
	4,  // 15: coresdk.activity_task.Cancel.details:type_name -> coresdk.activity_task.ActivityCancellationDetails
	7,  // 16: coresdk.activity_task.Start.HeaderFieldsEntry.value:type_name -> temporal.api.common.v1.Payload
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_temporal_sdk_core_activity_task_activity_task_proto_init() }
func file_temporal_sdk_core_activity_task_activity_task_proto_init() {
	if File_temporal_sdk_core_activity_task_activity_task_proto != nil {
		return
	}
	file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes[0].OneofWrappers = []any{
		(*ActivityTask_Start)(nil),
		(*ActivityTask_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_activity_task_activity_task_proto_rawDesc), len(file_temporal_sdk_core_activity_task_activity_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_sdk_core_activity_task_activity_task_proto_goTypes,
		DependencyIndexes: file_temporal_sdk_core_activity_task_activity_task_proto_depIdxs,
		EnumInfos:         file_temporal_sdk_core_activity_task_activity_task_proto_enumTypes,
		MessageInfos:      file_temporal_sdk_core_activity_task_activity_task_proto_msgTypes,
	}.Build()
	File_temporal_sdk_core_activity_task_activity_task_proto = out.File
	file_temporal_sdk_core_activity_task_activity_task_proto_goTypes = nil
	file_temporal_sdk_core_activity_task_activity_task_proto_depIdxs = nil
}
