// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: temporal/sdk/core/external_data/external_data.proto

package externaldata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalActivityMarkerData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint32                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// The number of attempts at execution before we recorded this result. Typically starts at 1,
	// but it is possible to start at a higher number when backing off using a timer.
	Attempt      uint32 `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ActivityId   string `protobuf:"bytes,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityType string `protobuf:"bytes,4,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	// You can think of this as "perceived completion time". It is the time the local activity thought
	// it was when it completed. Which could be different from wall-clock time because of workflow
	// replay. It's the WFT start time + the LA's runtime
	CompleteTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=complete_time,json=completeTime,proto3" json:"complete_time,omitempty"`
	// If set, this local activity conceptually is retrying after the specified backoff.
	// Implementation wise, they are really two different LA machines, but with the same type & input.
	// The retry starts with an attempt number > 1.
	Backoff *durationpb.Duration `protobuf:"bytes,6,opt,name=backoff,proto3" json:"backoff,omitempty"`
	// The time the LA was originally scheduled (wall clock time). This is used to track
	// schedule-to-close timeouts when timer-based backoffs are used
	OriginalScheduleTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=original_schedule_time,json=originalScheduleTime,proto3" json:"original_schedule_time,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LocalActivityMarkerData) Reset() {
	*x = LocalActivityMarkerData{}
	mi := &file_temporal_sdk_core_external_data_external_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalActivityMarkerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalActivityMarkerData) ProtoMessage() {}

func (x *LocalActivityMarkerData) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_external_data_external_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalActivityMarkerData.ProtoReflect.Descriptor instead.
func (*LocalActivityMarkerData) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_external_data_external_data_proto_rawDescGZIP(), []int{0}
}

func (x *LocalActivityMarkerData) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LocalActivityMarkerData) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *LocalActivityMarkerData) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *LocalActivityMarkerData) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *LocalActivityMarkerData) GetCompleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompleteTime
	}
	return nil
}

func (x *LocalActivityMarkerData) GetBackoff() *durationpb.Duration {
	if x != nil {
		return x.Backoff
	}
	return nil
}

func (x *LocalActivityMarkerData) GetOriginalScheduleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OriginalScheduleTime
	}
	return nil
}

type PatchedMarkerData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The patch id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Whether or not the patch is marked deprecated.
	Deprecated    bool `protobuf:"varint,2,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchedMarkerData) Reset() {
	*x = PatchedMarkerData{}
	mi := &file_temporal_sdk_core_external_data_external_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchedMarkerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchedMarkerData) ProtoMessage() {}

func (x *PatchedMarkerData) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_external_data_external_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchedMarkerData.ProtoReflect.Descriptor instead.
func (*PatchedMarkerData) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_external_data_external_data_proto_rawDescGZIP(), []int{1}
}

func (x *PatchedMarkerData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchedMarkerData) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

var File_temporal_sdk_core_external_data_external_data_proto protoreflect.FileDescriptor

const file_temporal_sdk_core_external_data_external_data_proto_rawDesc = "" +
	"\n" +
	"3temporal/sdk/core/external_data/external_data.proto\x12\x15coresdk.external_data\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x02\n" +
	"\x17LocalActivityMarkerData\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\rR\aattempt\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\tR\n" +
	"activityId\x12#\n" +
	"\ractivity_type\x18\x04 \x01(\tR\factivityType\x12?\n" +
	"\rcomplete_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fcompleteTime\x123\n" +
	"\abackoff\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\abackoff\x12P\n" +
	"\x16original_schedule_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x14originalScheduleTime\"C\n" +
	"\x11PatchedMarkerData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x02 \x01(\bR\n" +
	"deprecatedB2\xea\x02/Temporalio::Internal::Bridge::Api::ExternalDatab\x06proto3"

var (
	file_temporal_sdk_core_external_data_external_data_proto_rawDescOnce sync.Once
	file_temporal_sdk_core_external_data_external_data_proto_rawDescData []byte
)

func file_temporal_sdk_core_external_data_external_data_proto_rawDescGZIP() []byte {
	file_temporal_sdk_core_external_data_external_data_proto_rawDescOnce.Do(func() {
		file_temporal_sdk_core_external_data_external_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_external_data_external_data_proto_rawDesc), len(file_temporal_sdk_core_external_data_external_data_proto_rawDesc)))
	})
	return file_temporal_sdk_core_external_data_external_data_proto_rawDescData
}

var file_temporal_sdk_core_external_data_external_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_temporal_sdk_core_external_data_external_data_proto_goTypes = []any{
	(*LocalActivityMarkerData)(nil), // 0: coresdk.external_data.LocalActivityMarkerData
	(*PatchedMarkerData)(nil),       // 1: coresdk.external_data.PatchedMarkerData
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),     // 3: google.protobuf.Duration
}
var file_temporal_sdk_core_external_data_external_data_proto_depIdxs = []int32{
	2, // 0: coresdk.external_data.LocalActivityMarkerData.complete_time:type_name -> google.protobuf.Timestamp
	3, // 1: coresdk.external_data.LocalActivityMarkerData.backoff:type_name -> google.protobuf.Duration
	2, // 2: coresdk.external_data.LocalActivityMarkerData.original_schedule_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_temporal_sdk_core_external_data_external_data_proto_init() }
func file_temporal_sdk_core_external_data_external_data_proto_init() {
	if File_temporal_sdk_core_external_data_external_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_external_data_external_data_proto_rawDesc), len(file_temporal_sdk_core_external_data_external_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_sdk_core_external_data_external_data_proto_goTypes,
		DependencyIndexes: file_temporal_sdk_core_external_data_external_data_proto_depIdxs,
		MessageInfos:      file_temporal_sdk_core_external_data_external_data_proto_msgTypes,
	}.Build()
	File_temporal_sdk_core_external_data_external_data_proto = out.File
	file_temporal_sdk_core_external_data_external_data_proto_goTypes = nil
	file_temporal_sdk_core_external_data_external_data_proto_depIdxs = nil
}
