// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: temporal/sdk/core/workflow_completion/workflow_completion.proto

package workflowcompletion

import (
	corecommon "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/corecommon"
	workflowcommands "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/workflowcommands"
	v1 "go.temporal.io/api/enums/v1"
	v11 "go.temporal.io/api/failure/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Result of a single workflow activation, reported from lang to core
type WorkflowActivationCompletion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The run id from the workflow activation you are completing
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Types that are valid to be assigned to Status:
	//
	//	*WorkflowActivationCompletion_Successful
	//	*WorkflowActivationCompletion_Failed
	Status isWorkflowActivationCompletion_Status `protobuf_oneof:"status"`
	// Metrics for external payload storage downloads (retrievals) performed while processing
	// this activation. Only set when external storage retrieved payloads.
	PayloadDownloadMetrics *corecommon.ExternalStorageMetrics `protobuf:"bytes,4,opt,name=payload_download_metrics,json=payloadDownloadMetrics,proto3" json:"payload_download_metrics,omitempty"`
	// Metrics for external payload storage uploads (stores) performed while processing this
	// activation. Only set when external storage stored payloads.
	PayloadUploadMetrics *corecommon.ExternalStorageMetrics `protobuf:"bytes,5,opt,name=payload_upload_metrics,json=payloadUploadMetrics,proto3" json:"payload_upload_metrics,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WorkflowActivationCompletion) Reset() {
	*x = WorkflowActivationCompletion{}
	mi := &file_temporal_sdk_core_workflow_completion_workflow_completion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowActivationCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowActivationCompletion) ProtoMessage() {}

func (x *WorkflowActivationCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_workflow_completion_workflow_completion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowActivationCompletion.ProtoReflect.Descriptor instead.
func (*WorkflowActivationCompletion) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowActivationCompletion) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkflowActivationCompletion) GetStatus() isWorkflowActivationCompletion_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *WorkflowActivationCompletion) GetSuccessful() *Success {
	if x != nil {
		if x, ok := x.Status.(*WorkflowActivationCompletion_Successful); ok {
			return x.Successful
		}
	}
	return nil
}

func (x *WorkflowActivationCompletion) GetFailed() *Failure {
	if x != nil {
		if x, ok := x.Status.(*WorkflowActivationCompletion_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *WorkflowActivationCompletion) GetPayloadDownloadMetrics() *corecommon.ExternalStorageMetrics {
	if x != nil {
		return x.PayloadDownloadMetrics
	}
	return nil
}

func (x *WorkflowActivationCompletion) GetPayloadUploadMetrics() *corecommon.ExternalStorageMetrics {
	if x != nil {
		return x.PayloadUploadMetrics
	}
	return nil
}

type isWorkflowActivationCompletion_Status interface {
	isWorkflowActivationCompletion_Status()
}

type WorkflowActivationCompletion_Successful struct {
	Successful *Success `protobuf:"bytes,2,opt,name=successful,proto3,oneof"`
}

type WorkflowActivationCompletion_Failed struct {
	Failed *Failure `protobuf:"bytes,3,opt,name=failed,proto3,oneof"`
}

func (*WorkflowActivationCompletion_Successful) isWorkflowActivationCompletion_Status() {}

func (*WorkflowActivationCompletion_Failed) isWorkflowActivationCompletion_Status() {}

// Successful workflow activation with a list of commands generated by the workflow execution
type Success struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of commands to send back to the temporal server
	Commands []*workflowcommands.WorkflowCommand `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	// Any internal flags which the lang SDK used in the processing of this activation
	UsedInternalFlags []uint32 `protobuf:"varint,6,rep,packed,name=used_internal_flags,json=usedInternalFlags,proto3" json:"used_internal_flags,omitempty"`
	// The versioning behavior this workflow is currently using
	VersioningBehavior v1.VersioningBehavior `protobuf:"varint,7,opt,name=versioning_behavior,json=versioningBehavior,proto3,enum=temporal.api.enums.v1.VersioningBehavior" json:"versioning_behavior,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_temporal_sdk_core_workflow_completion_workflow_completion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_workflow_completion_workflow_completion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDescGZIP(), []int{1}
}

func (x *Success) GetCommands() []*workflowcommands.WorkflowCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Success) GetUsedInternalFlags() []uint32 {
	if x != nil {
		return x.UsedInternalFlags
	}
	return nil
}

func (x *Success) GetVersioningBehavior() v1.VersioningBehavior {
	if x != nil {
		return x.VersioningBehavior
	}
	return v1.VersioningBehavior(0)
}

// Failure to activate or execute a workflow
type Failure struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Failure *v11.Failure           `protobuf:"bytes,1,opt,name=failure,proto3" json:"failure,omitempty"`
	// Forces overriding the WFT failure cause
	ForceCause    v1.WorkflowTaskFailedCause `protobuf:"varint,2,opt,name=force_cause,json=forceCause,proto3,enum=temporal.api.enums.v1.WorkflowTaskFailedCause" json:"force_cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_temporal_sdk_core_workflow_completion_workflow_completion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_workflow_completion_workflow_completion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDescGZIP(), []int{2}
}

func (x *Failure) GetFailure() *v11.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *Failure) GetForceCause() v1.WorkflowTaskFailedCause {
	if x != nil {
		return x.ForceCause
	}
	return v1.WorkflowTaskFailedCause(0)
}

var File_temporal_sdk_core_workflow_completion_workflow_completion_proto protoreflect.FileDescriptor

const file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDesc = "" +
	"\n" +
	"?temporal/sdk/core/workflow_completion/workflow_completion.proto\x12\x1bcoresdk.workflow_completion\x1a%temporal/api/failure/v1/message.proto\x1a(temporal/api/enums/v1/failed_cause.proto\x1a$temporal/api/enums/v1/workflow.proto\x1a%temporal/sdk/core/common/common.proto\x1a;temporal/sdk/core/workflow_commands/workflow_commands.proto\"\x87\x03\n" +
	"\x1cWorkflowActivationCompletion\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12F\n" +
	"\n" +
	"successful\x18\x02 \x01(\v2$.coresdk.workflow_completion.SuccessH\x00R\n" +
	"successful\x12>\n" +
	"\x06failed\x18\x03 \x01(\v2$.coresdk.workflow_completion.FailureH\x00R\x06failed\x12`\n" +
	"\x18payload_download_metrics\x18\x04 \x01(\v2&.coresdk.common.ExternalStorageMetricsR\x16payloadDownloadMetrics\x12\\\n" +
	"\x16payload_upload_metrics\x18\x05 \x01(\v2&.coresdk.common.ExternalStorageMetricsR\x14payloadUploadMetricsB\b\n" +
	"\x06status\"\xdd\x01\n" +
	"\aSuccess\x12F\n" +
	"\bcommands\x18\x01 \x03(\v2*.coresdk.workflow_commands.WorkflowCommandR\bcommands\x12.\n" +
	"\x13used_internal_flags\x18\x06 \x03(\rR\x11usedInternalFlags\x12Z\n" +
	"\x13versioning_behavior\x18\a \x01(\x0e2).temporal.api.enums.v1.VersioningBehaviorR\x12versioningBehavior\"\x96\x01\n" +
	"\aFailure\x12:\n" +
	"\afailure\x18\x01 \x01(\v2 .temporal.api.failure.v1.FailureR\afailure\x12O\n" +
	"\vforce_cause\x18\x02 \x01(\x0e2..temporal.api.enums.v1.WorkflowTaskFailedCauseR\n" +
	"forceCauseB8\xea\x025Temporalio::Internal::Bridge::Api::WorkflowCompletionb\x06proto3"

var (
	file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDescOnce sync.Once
	file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDescData []byte
)

func file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDescGZIP() []byte {
	file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDescOnce.Do(func() {
		file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDesc), len(file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDesc)))
	})
	return file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDescData
}

var file_temporal_sdk_core_workflow_completion_workflow_completion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_temporal_sdk_core_workflow_completion_workflow_completion_proto_goTypes = []any{
	(*WorkflowActivationCompletion)(nil),      // 0: coresdk.workflow_completion.WorkflowActivationCompletion
	(*Success)(nil),                           // 1: coresdk.workflow_completion.Success
	(*Failure)(nil),                           // 2: coresdk.workflow_completion.Failure
	(*corecommon.ExternalStorageMetrics)(nil), // 3: coresdk.common.ExternalStorageMetrics
	(*workflowcommands.WorkflowCommand)(nil),  // 4: coresdk.workflow_commands.WorkflowCommand
	(v1.VersioningBehavior)(0),                // 5: temporal.api.enums.v1.VersioningBehavior
	(*v11.Failure)(nil),                       // 6: temporal.api.failure.v1.Failure
	(v1.WorkflowTaskFailedCause)(0),           // 7: temporal.api.enums.v1.WorkflowTaskFailedCause
}
var file_temporal_sdk_core_workflow_completion_workflow_completion_proto_depIdxs = []int32{
	1, // 0: coresdk.workflow_completion.WorkflowActivationCompletion.successful:type_name -> coresdk.workflow_completion.Success
	2, // 1: coresdk.workflow_completion.WorkflowActivationCompletion.failed:type_name -> coresdk.workflow_completion.Failure
	3, // 2: coresdk.workflow_completion.WorkflowActivationCompletion.payload_download_metrics:type_name -> coresdk.common.ExternalStorageMetrics
	3, // 3: coresdk.workflow_completion.WorkflowActivationCompletion.payload_upload_metrics:type_name -> coresdk.common.ExternalStorageMetrics
	4, // 4: coresdk.workflow_completion.Success.commands:type_name -> coresdk.workflow_commands.WorkflowCommand
	5, // 5: coresdk.workflow_completion.Success.versioning_behavior:type_name -> temporal.api.enums.v1.VersioningBehavior
	6, // 6: coresdk.workflow_completion.Failure.failure:type_name -> temporal.api.failure.v1.Failure
	7, // 7: coresdk.workflow_completion.Failure.force_cause:type_name -> temporal.api.enums.v1.WorkflowTaskFailedCause
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_temporal_sdk_core_workflow_completion_workflow_completion_proto_init() }
func file_temporal_sdk_core_workflow_completion_workflow_completion_proto_init() {
	if File_temporal_sdk_core_workflow_completion_workflow_completion_proto != nil {
		return
	}
	file_temporal_sdk_core_workflow_completion_workflow_completion_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkflowActivationCompletion_Successful)(nil),
		(*WorkflowActivationCompletion_Failed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDesc), len(file_temporal_sdk_core_workflow_completion_workflow_completion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_sdk_core_workflow_completion_workflow_completion_proto_goTypes,
		DependencyIndexes: file_temporal_sdk_core_workflow_completion_workflow_completion_proto_depIdxs,
		MessageInfos:      file_temporal_sdk_core_workflow_completion_workflow_completion_proto_msgTypes,
	}.Build()
	File_temporal_sdk_core_workflow_completion_workflow_completion_proto = out.File
	file_temporal_sdk_core_workflow_completion_workflow_completion_proto_goTypes = nil
	file_temporal_sdk_core_workflow_completion_workflow_completion_proto_depIdxs = nil
}
