// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: temporal/sdk/core/nexus/nexus.proto

package nexus

import (
	_ "github.com/temporalio/sdk-go-on-wasm-core/internal/corepb/corecommon"
	v1 "go.temporal.io/api/common/v1"
	v11 "go.temporal.io/api/failure/v1"
	v12 "go.temporal.io/api/nexus/v1"
	v13 "go.temporal.io/api/workflowservice/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NexusTaskCancelReason int32

const (
	// The nexus task is known to have timed out
	NexusTaskCancelReason_TIMED_OUT NexusTaskCancelReason = 0
	// The worker is shutting down
	NexusTaskCancelReason_WORKER_SHUTDOWN NexusTaskCancelReason = 1
)

// Enum value maps for NexusTaskCancelReason.
var (
	NexusTaskCancelReason_name = map[int32]string{
		0: "TIMED_OUT",
		1: "WORKER_SHUTDOWN",
	}
	NexusTaskCancelReason_value = map[string]int32{
		"TIMED_OUT":       0,
		"WORKER_SHUTDOWN": 1,
	}
)

func (x NexusTaskCancelReason) Enum() *NexusTaskCancelReason {
	p := new(NexusTaskCancelReason)
	*p = x
	return p
}

func (x NexusTaskCancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NexusTaskCancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_sdk_core_nexus_nexus_proto_enumTypes[0].Descriptor()
}

func (NexusTaskCancelReason) Type() protoreflect.EnumType {
	return &file_temporal_sdk_core_nexus_nexus_proto_enumTypes[0]
}

func (x NexusTaskCancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NexusTaskCancelReason.Descriptor instead.
func (NexusTaskCancelReason) EnumDescriptor() ([]byte, []int) {
	return file_temporal_sdk_core_nexus_nexus_proto_rawDescGZIP(), []int{0}
}

// Controls at which point to report back to lang when a nexus operation is cancelled
type NexusOperationCancellationType int32

const (
	// Wait for operation cancellation completion. Default.
	NexusOperationCancellationType_WAIT_CANCELLATION_COMPLETED NexusOperationCancellationType = 0
	// Do not request cancellation of the nexus operation if already scheduled
	NexusOperationCancellationType_ABANDON NexusOperationCancellationType = 1
	// Initiate a cancellation request for the Nexus operation and immediately report cancellation
	// to the caller. Note that it doesn't guarantee that cancellation is delivered to the operation if calling workflow exits before the delivery is done.
	// If you want to ensure that cancellation is delivered to the operation, use WAIT_CANCELLATION_REQUESTED.
	NexusOperationCancellationType_TRY_CANCEL NexusOperationCancellationType = 2
	// Request cancellation of the operation and wait for confirmation that the request was received.
	NexusOperationCancellationType_WAIT_CANCELLATION_REQUESTED NexusOperationCancellationType = 3
)

// Enum value maps for NexusOperationCancellationType.
var (
	NexusOperationCancellationType_name = map[int32]string{
		0: "WAIT_CANCELLATION_COMPLETED",
		1: "ABANDON",
		2: "TRY_CANCEL",
		3: "WAIT_CANCELLATION_REQUESTED",
	}
	NexusOperationCancellationType_value = map[string]int32{
		"WAIT_CANCELLATION_COMPLETED": 0,
		"ABANDON":                     1,
		"TRY_CANCEL":                  2,
		"WAIT_CANCELLATION_REQUESTED": 3,
	}
)

func (x NexusOperationCancellationType) Enum() *NexusOperationCancellationType {
	p := new(NexusOperationCancellationType)
	*p = x
	return p
}

func (x NexusOperationCancellationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NexusOperationCancellationType) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_sdk_core_nexus_nexus_proto_enumTypes[1].Descriptor()
}

func (NexusOperationCancellationType) Type() protoreflect.EnumType {
	return &file_temporal_sdk_core_nexus_nexus_proto_enumTypes[1]
}

func (x NexusOperationCancellationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NexusOperationCancellationType.Descriptor instead.
func (NexusOperationCancellationType) EnumDescriptor() ([]byte, []int) {
	return file_temporal_sdk_core_nexus_nexus_proto_rawDescGZIP(), []int{1}
}

// Used by core to resolve nexus operations.
type NexusOperationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*NexusOperationResult_Completed
	//	*NexusOperationResult_Failed
	//	*NexusOperationResult_Cancelled
	//	*NexusOperationResult_TimedOut
	Status        isNexusOperationResult_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NexusOperationResult) Reset() {
	*x = NexusOperationResult{}
	mi := &file_temporal_sdk_core_nexus_nexus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NexusOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusOperationResult) ProtoMessage() {}

func (x *NexusOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_nexus_nexus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusOperationResult.ProtoReflect.Descriptor instead.
func (*NexusOperationResult) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_nexus_nexus_proto_rawDescGZIP(), []int{0}
}

func (x *NexusOperationResult) GetStatus() isNexusOperationResult_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *NexusOperationResult) GetCompleted() *v1.Payload {
	if x != nil {
		if x, ok := x.Status.(*NexusOperationResult_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *NexusOperationResult) GetFailed() *v11.Failure {
	if x != nil {
		if x, ok := x.Status.(*NexusOperationResult_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *NexusOperationResult) GetCancelled() *v11.Failure {
	if x != nil {
		if x, ok := x.Status.(*NexusOperationResult_Cancelled); ok {
			return x.Cancelled
		}
	}
	return nil
}

func (x *NexusOperationResult) GetTimedOut() *v11.Failure {
	if x != nil {
		if x, ok := x.Status.(*NexusOperationResult_TimedOut); ok {
			return x.TimedOut
		}
	}
	return nil
}

type isNexusOperationResult_Status interface {
	isNexusOperationResult_Status()
}

type NexusOperationResult_Completed struct {
	Completed *v1.Payload `protobuf:"bytes,1,opt,name=completed,proto3,oneof"`
}

type NexusOperationResult_Failed struct {
	Failed *v11.Failure `protobuf:"bytes,2,opt,name=failed,proto3,oneof"`
}

type NexusOperationResult_Cancelled struct {
	Cancelled *v11.Failure `protobuf:"bytes,3,opt,name=cancelled,proto3,oneof"`
}

type NexusOperationResult_TimedOut struct {
	TimedOut *v11.Failure `protobuf:"bytes,4,opt,name=timed_out,json=timedOut,proto3,oneof"`
}

func (*NexusOperationResult_Completed) isNexusOperationResult_Status() {}

func (*NexusOperationResult_Failed) isNexusOperationResult_Status() {}

func (*NexusOperationResult_Cancelled) isNexusOperationResult_Status() {}

func (*NexusOperationResult_TimedOut) isNexusOperationResult_Status() {}

// A response to a Nexus task
type NexusTaskCompletion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for this task provided in the poll response
	TaskToken []byte `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	// Types that are valid to be assigned to Status:
	//
	//	*NexusTaskCompletion_Completed
	//	*NexusTaskCompletion_Error
	//	*NexusTaskCompletion_AckCancel
	//	*NexusTaskCompletion_Failure
	Status        isNexusTaskCompletion_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NexusTaskCompletion) Reset() {
	*x = NexusTaskCompletion{}
	mi := &file_temporal_sdk_core_nexus_nexus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NexusTaskCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusTaskCompletion) ProtoMessage() {}

func (x *NexusTaskCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_nexus_nexus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusTaskCompletion.ProtoReflect.Descriptor instead.
func (*NexusTaskCompletion) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_nexus_nexus_proto_rawDescGZIP(), []int{1}
}

func (x *NexusTaskCompletion) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *NexusTaskCompletion) GetStatus() isNexusTaskCompletion_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *NexusTaskCompletion) GetCompleted() *v12.Response {
	if x != nil {
		if x, ok := x.Status.(*NexusTaskCompletion_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in temporal/sdk/core/nexus/nexus.proto.
func (x *NexusTaskCompletion) GetError() *v12.HandlerError {
	if x != nil {
		if x, ok := x.Status.(*NexusTaskCompletion_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *NexusTaskCompletion) GetAckCancel() bool {
	if x != nil {
		if x, ok := x.Status.(*NexusTaskCompletion_AckCancel); ok {
			return x.AckCancel
		}
	}
	return false
}

func (x *NexusTaskCompletion) GetFailure() *v11.Failure {
	if x != nil {
		if x, ok := x.Status.(*NexusTaskCompletion_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isNexusTaskCompletion_Status interface {
	isNexusTaskCompletion_Status()
}

type NexusTaskCompletion_Completed struct {
	// The handler completed (successfully or not). Note that the response kind must match the
	// request kind (start or cancel).
	Completed *v12.Response `protobuf:"bytes,2,opt,name=completed,proto3,oneof"`
}

type NexusTaskCompletion_Error struct {
	// The handler could not complete the request for some reason. Deprecated, use failure.
	//
	// Deprecated: Marked as deprecated in temporal/sdk/core/nexus/nexus.proto.
	Error *v12.HandlerError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type NexusTaskCompletion_AckCancel struct {
	// The lang SDK acknowledges that it is responding to a `CancelNexusTask` and thus the
	// response is irrelevant. This is not the only way to respond to a cancel, the other
	// variants can still be used, but this variant should be used when the handler was aborted
	// by cancellation.
	AckCancel bool `protobuf:"varint,4,opt,name=ack_cancel,json=ackCancel,proto3,oneof"`
}

type NexusTaskCompletion_Failure struct {
	// The handler could not complete the request for some reason.
	Failure *v11.Failure `protobuf:"bytes,5,opt,name=failure,proto3,oneof"`
}

func (*NexusTaskCompletion_Completed) isNexusTaskCompletion_Status() {}

func (*NexusTaskCompletion_Error) isNexusTaskCompletion_Status() {}

func (*NexusTaskCompletion_AckCancel) isNexusTaskCompletion_Status() {}

func (*NexusTaskCompletion_Failure) isNexusTaskCompletion_Status() {}

type NexusTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Variant:
	//
	//	*NexusTask_Task
	//	*NexusTask_CancelTask
	Variant isNexusTask_Variant `protobuf_oneof:"variant"`
	// The deadline for this request, parsed from the "Request-Timeout" header.
	// Only set when variant is `task` and the header was present with a valid value.
	// Represented as an absolute timestamp.
	RequestDeadline *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=request_deadline,json=requestDeadline,proto3" json:"request_deadline,omitempty"`
	// The endpoint this request was addressed to. Extracted from the request for convenient access.
	// Only set when variant is `task`.
	Endpoint      string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NexusTask) Reset() {
	*x = NexusTask{}
	mi := &file_temporal_sdk_core_nexus_nexus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NexusTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusTask) ProtoMessage() {}

func (x *NexusTask) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_nexus_nexus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusTask.ProtoReflect.Descriptor instead.
func (*NexusTask) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_nexus_nexus_proto_rawDescGZIP(), []int{2}
}

func (x *NexusTask) GetVariant() isNexusTask_Variant {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *NexusTask) GetTask() *v13.PollNexusTaskQueueResponse {
	if x != nil {
		if x, ok := x.Variant.(*NexusTask_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *NexusTask) GetCancelTask() *CancelNexusTask {
	if x != nil {
		if x, ok := x.Variant.(*NexusTask_CancelTask); ok {
			return x.CancelTask
		}
	}
	return nil
}

func (x *NexusTask) GetRequestDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestDeadline
	}
	return nil
}

func (x *NexusTask) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type isNexusTask_Variant interface {
	isNexusTask_Variant()
}

type NexusTask_Task struct {
	// A nexus task from server
	Task *v13.PollNexusTaskQueueResponse `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type NexusTask_CancelTask struct {
	// A request by Core to notify an in-progress operation handler that it should cancel. This
	// is distinct from a `CancelOperationRequest` from the server, which results from the user
	// requesting the cancellation of an operation. Handling this variant should result in
	// something like cancelling a cancellation token given to the user's operation handler.
	//
	// These do not count as a separate task for the purposes of completing all issued tasks,
	// but rather count as a sort of modification to the already-issued task which is being
	// cancelled.
	//
	// EX: Core knows the nexus operation has timed out, and it does not make sense for the
	// user's operation handler to continue doing work.
	CancelTask *CancelNexusTask `protobuf:"bytes,2,opt,name=cancel_task,json=cancelTask,proto3,oneof"`
}

func (*NexusTask_Task) isNexusTask_Variant() {}

func (*NexusTask_CancelTask) isNexusTask_Variant() {}

type CancelNexusTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The task token from the PollNexusTaskQueueResponse
	TaskToken []byte `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	// Why Core is asking for this operation to be cancelled
	Reason        NexusTaskCancelReason `protobuf:"varint,2,opt,name=reason,proto3,enum=coresdk.nexus.NexusTaskCancelReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelNexusTask) Reset() {
	*x = CancelNexusTask{}
	mi := &file_temporal_sdk_core_nexus_nexus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelNexusTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelNexusTask) ProtoMessage() {}

func (x *CancelNexusTask) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_sdk_core_nexus_nexus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelNexusTask.ProtoReflect.Descriptor instead.
func (*CancelNexusTask) Descriptor() ([]byte, []int) {
	return file_temporal_sdk_core_nexus_nexus_proto_rawDescGZIP(), []int{3}
}

func (x *CancelNexusTask) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *CancelNexusTask) GetReason() NexusTaskCancelReason {
	if x != nil {
		return x.Reason
	}
	return NexusTaskCancelReason_TIMED_OUT
}

var File_temporal_sdk_core_nexus_nexus_proto protoreflect.FileDescriptor

const file_temporal_sdk_core_nexus_nexus_proto_rawDesc = "" +
	"\n" +
	"#temporal/sdk/core/nexus/nexus.proto\x12\rcoresdk.nexus\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$temporal/api/common/v1/message.proto\x1a%temporal/api/failure/v1/message.proto\x1a#temporal/api/nexus/v1/message.proto\x1a6temporal/api/workflowservice/v1/request_response.proto\x1a%temporal/sdk/core/common/common.proto\"\xa0\x02\n" +
	"\x14NexusOperationResult\x12?\n" +
	"\tcompleted\x18\x01 \x01(\v2\x1f.temporal.api.common.v1.PayloadH\x00R\tcompleted\x12:\n" +
	"\x06failed\x18\x02 \x01(\v2 .temporal.api.failure.v1.FailureH\x00R\x06failed\x12@\n" +
	"\tcancelled\x18\x03 \x01(\v2 .temporal.api.failure.v1.FailureH\x00R\tcancelled\x12?\n" +
	"\ttimed_out\x18\x04 \x01(\v2 .temporal.api.failure.v1.FailureH\x00R\btimedOutB\b\n" +
	"\x06status\"\x9f\x02\n" +
	"\x13NexusTaskCompletion\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12?\n" +
	"\tcompleted\x18\x02 \x01(\v2\x1f.temporal.api.nexus.v1.ResponseH\x00R\tcompleted\x12?\n" +
	"\x05error\x18\x03 \x01(\v2#.temporal.api.nexus.v1.HandlerErrorB\x02\x18\x01H\x00R\x05error\x12\x1f\n" +
	"\n" +
	"ack_cancel\x18\x04 \x01(\bH\x00R\tackCancel\x12<\n" +
	"\afailure\x18\x05 \x01(\v2 .temporal.api.failure.v1.FailureH\x00R\afailureB\b\n" +
	"\x06status\"\x8f\x02\n" +
	"\tNexusTask\x12Q\n" +
	"\x04task\x18\x01 \x01(\v2;.temporal.api.workflowservice.v1.PollNexusTaskQueueResponseH\x00R\x04task\x12A\n" +
	"\vcancel_task\x18\x02 \x01(\v2\x1e.coresdk.nexus.CancelNexusTaskH\x00R\n" +
	"cancelTask\x12E\n" +
	"\x10request_deadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0frequestDeadline\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpointB\t\n" +
	"\avariant\"n\n" +
	"\x0fCancelNexusTask\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12<\n" +
	"\x06reason\x18\x02 \x01(\x0e2$.coresdk.nexus.NexusTaskCancelReasonR\x06reason*;\n" +
	"\x15NexusTaskCancelReason\x12\r\n" +
	"\tTIMED_OUT\x10\x00\x12\x13\n" +
	"\x0fWORKER_SHUTDOWN\x10\x01*\x7f\n" +
	"\x1eNexusOperationCancellationType\x12\x1f\n" +
	"\x1bWAIT_CANCELLATION_COMPLETED\x10\x00\x12\v\n" +
	"\aABANDON\x10\x01\x12\x0e\n" +
	"\n" +
	"TRY_CANCEL\x10\x02\x12\x1f\n" +
	"\x1bWAIT_CANCELLATION_REQUESTED\x10\x03B+\xea\x02(Temporalio::Internal::Bridge::Api::Nexusb\x06proto3"

var (
	file_temporal_sdk_core_nexus_nexus_proto_rawDescOnce sync.Once
	file_temporal_sdk_core_nexus_nexus_proto_rawDescData []byte
)

func file_temporal_sdk_core_nexus_nexus_proto_rawDescGZIP() []byte {
	file_temporal_sdk_core_nexus_nexus_proto_rawDescOnce.Do(func() {
		file_temporal_sdk_core_nexus_nexus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_nexus_nexus_proto_rawDesc), len(file_temporal_sdk_core_nexus_nexus_proto_rawDesc)))
	})
	return file_temporal_sdk_core_nexus_nexus_proto_rawDescData
}

var file_temporal_sdk_core_nexus_nexus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_temporal_sdk_core_nexus_nexus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_temporal_sdk_core_nexus_nexus_proto_goTypes = []any{
	(NexusTaskCancelReason)(0),             // 0: coresdk.nexus.NexusTaskCancelReason
	(NexusOperationCancellationType)(0),    // 1: coresdk.nexus.NexusOperationCancellationType
	(*NexusOperationResult)(nil),           // 2: coresdk.nexus.NexusOperationResult
	(*NexusTaskCompletion)(nil),            // 3: coresdk.nexus.NexusTaskCompletion
	(*NexusTask)(nil),                      // 4: coresdk.nexus.NexusTask
	(*CancelNexusTask)(nil),                // 5: coresdk.nexus.CancelNexusTask
	(*v1.Payload)(nil),                     // 6: temporal.api.common.v1.Payload
	(*v11.Failure)(nil),                    // 7: temporal.api.failure.v1.Failure
	(*v12.Response)(nil),                   // 8: temporal.api.nexus.v1.Response
	(*v12.HandlerError)(nil),               // 9: temporal.api.nexus.v1.HandlerError
	(*v13.PollNexusTaskQueueResponse)(nil), // 10: temporal.api.workflowservice.v1.PollNexusTaskQueueResponse
	(*timestamppb.Timestamp)(nil),          // 11: google.protobuf.Timestamp
}
var file_temporal_sdk_core_nexus_nexus_proto_depIdxs = []int32{
	6,  // 0: coresdk.nexus.NexusOperationResult.completed:type_name -> temporal.api.common.v1.Payload
	7,  // 1: coresdk.nexus.NexusOperationResult.failed:type_name -> temporal.api.failure.v1.Failure
	7,  // 2: coresdk.nexus.NexusOperationResult.cancelled:type_name -> temporal.api.failure.v1.Failure
	7,  // 3: coresdk.nexus.NexusOperationResult.timed_out:type_name -> temporal.api.failure.v1.Failure
	8,  // 4: coresdk.nexus.NexusTaskCompletion.completed:type_name -> temporal.api.nexus.v1.Response
	9,  // 5: coresdk.nexus.NexusTaskCompletion.error:type_name -> temporal.api.nexus.v1.HandlerError
	7,  // 6: coresdk.nexus.NexusTaskCompletion.failure:type_name -> temporal.api.failure.v1.Failure
	10, // 7: coresdk.nexus.NexusTask.task:type_name -> temporal.api.workflowservice.v1.PollNexusTaskQueueResponse
	5,  // 8: coresdk.nexus.NexusTask.cancel_task:type_name -> coresdk.nexus.CancelNexusTask
	11, // 9: coresdk.nexus.NexusTask.request_deadline:type_name -> google.protobuf.Timestamp
	0,  // 10: coresdk.nexus.CancelNexusTask.reason:type_name -> coresdk.nexus.NexusTaskCancelReason
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_temporal_sdk_core_nexus_nexus_proto_init() }
func file_temporal_sdk_core_nexus_nexus_proto_init() {
	if File_temporal_sdk_core_nexus_nexus_proto != nil {
		return
	}
	file_temporal_sdk_core_nexus_nexus_proto_msgTypes[0].OneofWrappers = []any{
		(*NexusOperationResult_Completed)(nil),
		(*NexusOperationResult_Failed)(nil),
		(*NexusOperationResult_Cancelled)(nil),
		(*NexusOperationResult_TimedOut)(nil),
	}
	file_temporal_sdk_core_nexus_nexus_proto_msgTypes[1].OneofWrappers = []any{
		(*NexusTaskCompletion_Completed)(nil),
		(*NexusTaskCompletion_Error)(nil),
		(*NexusTaskCompletion_AckCancel)(nil),
		(*NexusTaskCompletion_Failure)(nil),
	}
	file_temporal_sdk_core_nexus_nexus_proto_msgTypes[2].OneofWrappers = []any{
		(*NexusTask_Task)(nil),
		(*NexusTask_CancelTask)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_sdk_core_nexus_nexus_proto_rawDesc), len(file_temporal_sdk_core_nexus_nexus_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_sdk_core_nexus_nexus_proto_goTypes,
		DependencyIndexes: file_temporal_sdk_core_nexus_nexus_proto_depIdxs,
		EnumInfos:         file_temporal_sdk_core_nexus_nexus_proto_enumTypes,
		MessageInfos:      file_temporal_sdk_core_nexus_nexus_proto_msgTypes,
	}.Build()
	File_temporal_sdk_core_nexus_nexus_proto = out.File
	file_temporal_sdk_core_nexus_nexus_proto_goTypes = nil
	file_temporal_sdk_core_nexus_nexus_proto_depIdxs = nil
}
